### ISSUE TITLE
1.8 Update

### ISSUE THREAD

**Issue by Wild1145** [Pravian/BukkitLib#5] opened 2015-01-20 20:15 UTC
With the 1.8 update there are some notable issues, most notable within the plugin metrics system so far, it causes a lot of log spam...

Just wanted to know if there will be a update and when we should expect it.

**Comment by WickedGamingUK** [comment] 2015-01-25 11:56
This is the error, by the way:

    org.apache.commons.lang.UnhandledException: Plugin TranxCraft v1.0 generated an exception while executing task 2
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at net.pravian.bukkitlib.InternalMetrics.postPlugin(InternalMetrics.java:215)
	at net.pravian.bukkitlib.InternalMetrics.access$300(InternalMetrics.java:57)
	at net.pravian.bukkitlib.InternalMetrics$1.run(InternalMetrics.java:158)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by WickedGamingUK** [comment] 2015-02-01 15:58
I forgot to reference this issue, but this has been resolved via 1ce33945408b262b29b599d75c82ebc7c3a678f4.

**Closed** 2015-02-02 20:52 UTC
Labels: bug
